> library(readr)
library(pROC)
 library(tidyverse)
 library(tableone)
 library(ggplot2)
 sepsis <- read_csv("F:/workstation/sepsis.csv")
 sepsis$admitdxname <- as.factor(sepsis$admitdxname)
 sepsis$unittype <- as.factor(sepsis$unittype)
 sepsis$gender <- as.factor(sepsis$gender)
 sepsis$hosp_mortality <- as.factor(sepsis$hosp_mortality)
 sepsis$icu_mortality <- as.factor(sepsis$icu_mortality)
 sepsis$ethnicity <- as.factor(sepsis$ethnicity)
 roc_rdw <- roc(data$hosp_mortality,data$rdw)
 plot(roc_rdw, print.auc=TRUE, auc.polygon=TRUE, grid=c(0.1, 0.2),grid.col=c("green", "red"), max.auc.polygon=TRUE,auc.polygon.col="skyblue", print.thres=TRUE)
rdw_group <- cut(data$rdw, breaks = c(-Inf,14.5,Inf),labels = c('normal','high') )
rdw_group2 <- cut(data$rdw, breaks = c(-Inf,15.75,Inf),labels = c('normal','high') )
 data <- cbind(data[,],rdw_group,rdw_group2)
 pre1 <- glm(hosp_mortality~rdw_group+sofa+apache_iv,data=data,family = binomial)
exp(confint(pre1))
exp(coef(pre1))
 data[which(data$admissionheight<20),12] <- NA
 data[which(data$admissionweight<20),13] <- NA
 data <- data %>% mutate(MAP = round((sbp+2*dbp)/3,1))
data <- data %>% mutate(BMI = round(admissionweight*10000/(admissionheight*admissionheight),2))
 missing.percent <- unlist(lapply(data, function(x) sum(is.na(x))))/nrow(data)
 vars <- c('age','admitdxname','gender','ethnicity','icu_mortality','icu_los_hours','hosp_mortality','sofa',"apache_iv",'BMI','MAP','hr','t','rdw','mch','mchc','albumin','creatinine','glucose','wbc','hematocrit','hemoglobin','platelet')
 tableOne <- CreateTableOne(vars = vars, strata = c("rdw_group"), data = data, testExact = fisher.test, testNonNormal = kruskal.test)
 p1<-print(tableOne, nonnormal=c('age','sofa',"apache_iv",'icu_los_hours','BMI','MAP','hr','t','rdw','mch','mchc','albumin','creatinine','glucose','wbc','hematocrit','hemoglobin','platelet'),argsExact=c('gender','ethnicity','admitdxname','icu_mortalityta','hosp_mortality'))
write.csv(p1,file = "D:\\p1.csv")c
 tableall <- CreateTableOne(vars = vars, data = data)
 p2<-print(tableall, nonnormal=c('age','sofa',"apache_iv",'icu_los_hours','BMI','MAP','hr','t','rdw','mch','mchc','albumin','creatinine','glucose','wbc','hematocrit','hemoglobin','platelet'),argsExact=c('gender','ethnicity','admitdxname','icu_mortalityta','hosp_mortality'))
 write.csv(p2,file = "D:\\p2.csv")> micedata <- data[,c(3,7,8,9,10,11,14,18,23,25,26,27,29,30,36,37,38,42,43,44,45,46)]
 imp <- mice(micedata,seed = 8177)
 fit <- with(imp,glm(hosp_mortality~age+sofa+apache_iv+albumin+creatinine+glucose+hematocrit+hemoglobin+platelet+potassium+wbc+MAP+BMI+rdw_group,family = binomial))
 pooled <- pool(fit)
rdw_g <- cut(data$rdw, breaks = c(-Inf,14.5,Inf),labels = c('0','1') )
 data_roc <- cbind(data[,],rdw_g)
 data_roc$rdw_g <- as.integer(data_roc$rdw_g)
roc.list <- roc(hosp_mortality ~ rdw_g+ sofa + apache_iv, data = data_roc)
ggroc(roc.list, size = 1.2,alpha=.8)+guides(color=guide_legend(title = NULL))+scale_color_discrete(labels=c('RDW','SOFA','APACHE ¢ô'))+theme(legend.position=c(0.9,0.1))+theme(legend.key = element_blank())+theme(legend.background = element_blank())
 ci.auc(hosp_mortality~rdw,data=data)
 ci(hosp_mortality~sofa,data=data)
 ci(hosp_mortality~apahce_iv,data=data)
m1 <- glm(hosp_mortality ~ sofa,family = binomial('logit'),data = data_new,x=TRUE)
m2 <- glm(hosp_mortality ~ sofa + rdw,family = binomial('logit'),data = data_new,x=TRUE)
mm1 <- predRisk(m1)
mm2 <- predRisk(m2)
reclassification(data=data_new,cOutcome = 5,predrisk1 = mm1,predrisk2 = mm2,cutoff=c(0,0.3,0.60,1))
data_new <- data[,c(7,10,11,14)]
tmp <- as.numeric(data_new[,1])
tmp <- tmp-1
cbind(data_new,tmp)
reclassification(data=data_new,cOutcome = 5,predrisk1 = mm1,predrisk2 = mm2,cutoff=c(0,0.3,0.60,1))
m3 <- glm(hosp_mortality ~ apache_iv,family = binomial('logit'),data = data_new,x=TRUE)
m4 <- glm(hosp_mortality ~ apache_iv + rdw,family = binomial('logit'),data = data_new,x=TRUE)
mm3 <- predRisk(m3)
mm4 <- predRisk(m4)
reclassification(data=data_new,cOutcome = 5,predrisk1 = mm3,predrisk2 = mm4,cutoff=c(0,0.3,0.60,1))
 ggplot(data,aes(admitdxname,rdw))+geom_boxplot(position='dodge',aes(fill=hosp_mortality))+scale_y_continuous(name = "RDW (%)",limits = c(10,35))+scale_x_discrete(name= "The source of sepsis",labels=c('Cutaneous','Gastrointestinal','Gynecologic','Others','Pulmonary','Urinary','Unknown'))+guides(fill=guide_legend(title='Hospital Mortality'))+scale_fill_discrete(labels=c('Alive','Dead'))
 data1 <- subset(data,admitdxname=='Sepsis, cutaneous/soft tissue')
 g1 <- glm(hosp_mortality~rdw_group+sofa+apache_iv,family = binomial,data = data1)
 exp(confint(g1))
 exp(coef(g1))
 summary(g1)
data2 <- subset(data,admitdxname=='Sepsis, GI')
g2 <- glm(hosp_mortality~rdw_group+sofa+apache_iv,family = binomial,data = data2)
exp(confint(g2))
exp(coef(g2))
summary(g2)
data3 <- subset(data,admitdxname=='Sepsis, other')
g3 <- glm(hosp_mortality~rdw_group+sofa+apache_iv,family = binomial,data = data3)
exp(confint(g3))
exp(coef(g3))
summary(g3)
data4 <- subset(data,admitdxname=='Sepsis, pulmonary')
g4 <- glm(hosp_mortality~rdw_group+sofa+apache_iv,family = binomial,data = data4)
exp(confint(g4))
exp(coef(g4))
summary(g4)
data5 <- subset(data,admitdxname=='Sepsis, renal/UTI (including bladder)')
g5 <- glm(hosp_mortality~rdw_group+sofa+apache_iv,family = binomial,data = data5)
exp(confint(g5))
exp(coef(g5))
summary(g5)
data6 <- subset(data,admitdxname=='Sepsis, unknown')
g6 <- glm(hosp_mortality~rdw_group+sofa+apache_iv,family = binomial,data = data6)
exp(confint(g6))
exp(coef(g6))
summary(g6)
data_sec<-subset(data,hosp_mortality==0)